swagger: "2.0"
info:
  description: "AWS Infrastructure Audit tool"
  version: "0.0.1"
  title: "AWS Infra Audit Service"
basePath: "/api/v1"
schemes:
- "https"
paths:
  /security-group/{securityGroupId}:
    get:
      summary: "Get details about security group."
      description: "Return details about security group."
      operationId: "getSecurityGroupById"
      produces:
        - "application/json"
      parameters:
        - name: "securityGroupId"
          in: path
          required: true
          type: string
          description: "Security group id."
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/SecurityGroup"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
        404:
          description: "Not Found"
        500:
          description: "Internal Server Error"
      x-amazon-apigateway-request-validators:
        basic:
          validateRequestParameters: true
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:123456789012:function:SecurityGroupInfo/invocations"
        responses:
          default:
            statusCode: 200
  /ebs/{ebsVolumeId}:
    get:
      summary: "Get details about EBS volume."
      description: "Return details about EBS volume."
      operationId: "getEBSVolumeById"
      produces:
        - "application/json"
      parameters:
        - name: "ebsVolumeId"
          in: path
          required: true
          type: string
          description: "EBS volume id."
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/EBSVolume"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
        404:
          description: "Not Found"
        500:
          description: "Internal Server Error"
      x-amazon-apigateway-request-validators:
        basic:
          validateRequestParameters: true
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:123456789012:function:EBSVolumeInfo/invocations"
        responses:
          default:
            statusCode: 200
definitions:
  SecurityGroup:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      description:
        type: "string"
      vpc_id:
        type: "string"
  EBSVolume:
    type: "object"
    properties:
      id:
        type: "string"
      encrypted:
        type: "boolean"
